"""db init

Revision ID: 64c4f43b8b3f
Revises: 
Create Date: 2019-04-04 18:08:05.351960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c4f43b8b3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('passwd', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='unique_email_user'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('nickname', name='unique_nickname_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
