"""fixing primary key

Revision ID: 8fa00db3ce76
Revises: 38715b22b1e2
Create Date: 2019-04-27 16:39:14.550611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa00db3ce76'
down_revision = '38715b22b1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
