version: '3.6'

services:
  app:
    command: gunicorn -c gunicorn.ini runserver:APP_GUNICORN
    environment:
        - BOTTLE_ENVIRON=prod

  web_server:
    build: ./nginx
    ports:
      - 8080:8080
      - 80:80
    depends_on:
      - app
    networks:
      - back
