"""migrate by invoke

Revision ID: d1a028135e32
Revises: 
Create Date: 2019-04-12 21:27:19.047294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a028135e32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_user_id'),
    sa.UniqueConstraint('email', name='unique_email_user'),
    sa.UniqueConstraint('nickname', name='unique_nickname_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
